### ISSUE TITLE
Crash when we change folders too quickly

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#581]
## What Happened

If we change folders too quickly (while Mail is busy loading its content) we encounter an application crash. This does not happen allways, but is well enough reproducible if we use the arrow keys to quickly switch between grouped folders.

## Expected Behavior

The app should not crash, but sucessfuly display all messages of the currently selected folder.

## Steps to Reproduce

1. Start Mail and wait till it is fully ready and all messages of the currently selected folder are loaded.
2. Select the first folder underneath the "All Mailboxes" section
3. Use up and down arrow keys to quickly navigate between first and second folder in the "All Mailboxes" section
4. Eventually the app crashes

### Logs

<details>
  <summary>Expand to see the backtrace.</summary>

  ```
  (gdb) backtrace
#0  0x00007ffff709b428 in camel_message_info_get_date_received () at /lib/x86_64-linux-gnu/libcamel-1.2.so.62
#1  0x00005555555962ef in mail_conversation_item_model_get_newest_timestamp (node=0x7fffffffd5c0, highest=1620035621) at ../src/ConversationList/ConversationItemModel.vala:168
#2  0x00005555555964a7 in mail_conversation_item_model_get_newest_timestamp (node=0x7fffffffd640, highest=-1) at ../src/ConversationList/ConversationItemModel.vala:173
#3  0x00005555555970d0 in mail_conversation_item_model_get_timestamp (self=0x555556508950) at ../src/ConversationList/ConversationItemModel.vala:142
#4  0x000055555559a902 in mail_conversation_list_box_thread_sort_function (item1=0x555556508950, item2=0x5555570a6d90) at ../src/ConversationList/ConversationListBox.vala:253
#5  0x000055555559cbe0 in _mail_conversation_list_box_thread_sort_function_gcompare_data_func (a=0x555556508950, b=0x5555570a6d90, self=0x0) at ConversationListBox.c:3163
#6  0x00007ffff7ee54fc in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7ee59df in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7ee68b4 in g_sequence_insert_sorted_iter () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7ee6998 in g_sequence_insert_sorted () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x000055555559fb5f in mail_conversation_list_store_add (self=0x5555559a79e0, data=0x5555570a6d90) at ../src/ConversationList/ConversationListStore.vala:81
#11 0x000055555559a835 in mail_conversation_list_box_add_conversation_item
    (self=0x5555559b2290, child=0x555555ef0660, service_uid=0x555555d9bcb0 "f59ce275647d46e0f964bce1a4359fbe4c24483c") at ../src/ConversationList/ConversationListBox.vala:249
#12 0x0000555555598c53 in mail_conversation_list_box_load_folder_co (_data_=0x555555ef03c0) at ../src/ConversationList/ConversationListBox.vala:158
#13 0x0000555555597d8b in mail_conversation_list_box_load_folder_ready (source_object=0x555555d73170, _res_=0x555555ddf010, _user_data_=0x555555ef03c0)
    at ../src/ConversationList/ConversationListBox.vala:145
#14 0x00007ffff72d4f49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff72d4f8d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007ffff7ecb04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff7ecb400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff7ecb4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff7302fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x00005555555708e4 in _vala_main (args=0x7fffffffdca8, args_length1=1) at ../src/Application.vala:123
#21 0x000055555557092b in main (argc=1, argv=0x7fffffffdca8) at ../src/Application.vala:121
  ```
</details>

**Comment by marbetschar** [comment]
Potential duplicate of #608

**Comment by marbetschar** [comment]
Closing as duplicate of https://github.com/elementary/mail/issues/650
