### ISSUE TITLE
Randomly Crashes

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#608]
## What Happened

Sometimes Mail crashes at random. It seems when a different folder is selected. I'm unable to 100% reproduce the issue, but the following is printed on the command line:

```
(io.elementary.mail:16338): camel-CRITICAL **: 10:45:47.779: camel_folder_get_uids: assertion 'CAMEL_IS_FOLDER (folder)' failed
Segmentation fault (core dumped)
```

## Expected Behavior

Mail should not crash when changing folders.

## Backtrace

```
(gdb) backtrace
#0  0x00007f751ad4600d in camel_folder_thread_messages_apply () at /lib/x86_64-linux-gnu/libcamel-1.2.so.62
#1  0x000055b147cb28f4 in mail_conversation_list_box_folder_changed
    (self=0x55b1495082e0, change_info=0x7f74f400d890, service_uid=0x55b14994a760 "2aa642074ba145733495c5b2771f1fbe8f9ab7fe", cancellable=0x55b14a0147a0) at ../src/ConversationList/ConversationListBox.vala:186
#2  0x000055b147cb0cc8 in _____________lambda21_ (_data11_=0x55b1493dba60, change_info=0x7f74f400d890)
    at ../src/ConversationList/ConversationListBox.vala:146
#3  0x000055b147cb0cf5 in ______________lambda21__camel_folder_changed (_sender=0x7f74f401fae0, changes=0x7f74f400d890, self=0x55b1493dba60)
    at ../src/ConversationList/ConversationListBox.vala:146
#4  0x00007f751bb5e802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f751bb72814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f751bb7dbbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f751bb7e0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f751ad4690d in  () at /lib/x86_64-linux-gnu/libcamel-1.2.so.62
#9  0x00007f751bbfc04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f751bbfc400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f751bbfc4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f751afc6fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x000055b147c87e04 in _vala_main (args=0x7ffefcd19278, args_length1=1) at ../src/Application.vala:123
#14 0x000055b147c87e4b in main (argc=1, argv=0x7ffefcd19278) at ../src/Application.vala:121
```

**Comment by marbetschar** [comment]
FWIW I configured multiple accounts: Two Office365 and one Yandex to be exact.
