### ISSUE TITLE
Mail rendering issue

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#697]
## What Happened

Some mails are not rendered and the Terminal shows the following error:

```
** (io.elementary.mail:41273): CRITICAL **: 20:55:49.891: mail_web_view_add_internal_resource: assertion 'name != NULL' failed
```

## Expected Behavior

The mail should be rendered w/o any error.

## Steps to Reproduce

1. Try to open a marketing mail from Apple in elementary Mail
2. You will see that the mail is not rendered at all

### Logs

Full backtrace:

```
(gdb) backtrace
#0  0x00007ffff7ede295 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7edf579 in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7edf743 in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x0000555555580e08 in mail_web_view_add_internal_resource (self=0x5555560168b0, name=0x0, data=0x55555605ead0) at ../src/WebView.vala:172
#4  0x00005555555c6b83 in mail_message_list_item_handle_inline_mime_co (_data_=0x555555f9ad50) at ../src/MessageList/MessageListItem.vala:591
#5  0x00005555555c662e in mail_message_list_item_handle_inline_mime_ready (source_object=0x7fffcc001b00, _res_=0x7fffc8008620, _user_data_=0x555555f9ad50)
    at ../src/MessageList/MessageListItem.vala:583
#6  0x00007ffff7274f49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff7274f8d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007ffff7ed804e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7ed8400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7ed84a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff72a2fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x0000555555574622 in _vala_main (args=0x7fffffffdb48, args_length1=1) at ../src/Application.vala:142
#13 0x0000555555574669 in main (argc=1, argv=0x7fffffffdb48) at ../src/Application.vala:140
```

## Platform Information

elementary OS 6 stable.

**Comment by KeironO** [comment]
If you ask me, having an Apple marketing email sounds more more like a feature as opposed to a bug.

**Comment by masuyamakurai** [comment]
had the same problem
![image](https://user-images.githubusercontent.com/3955500/141687848-3f264c16-4325-468f-89a3-baa9f8cbd7ff.png)

**Comment by itmm** [comment]
> had the same problem with some email from my work
> 
> ![image](https://user-images.githubusercontent.com/3955500/141687848-3f264c16-4325-468f-89a3-baa9f8cbd7ff.png)

I believe there is no big harm in the first two messages, but they are fixed with the Pull Request #736.
