### ISSUE TITLE
folder_changed causes crash

### ISSUE THREAD

**Issue by dbhowell** [elementary/mail#700]
## What Happened
Occasionally mail will crash when an update to a folder happens on the server and mail is trying to update the conversation list. 

## Expected Behavior
When a folder is changed on the server, mail should reflect those changes without crashing.

## Steps to Reproduce

1. Login to mailbox via an alternative method (e.g. webmail)
2. Start mail app
3. Using alternative method, delete TWO emails from the server
4. mail will crash as it is trying to reference an already deleted item

### Logs
```
#0  0x00007ffff7e646d9 in g_type_check_instance_is_fundamentally_a () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7e457f0 in g_object_get () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00005555555a6493 in mail_conversation_item_model_get_deleted (self=0x555557184a50) at ../src/ConversationList/ConversationItemModel.vala:145
#3  0x00005555555ad134 in _mail_conversation_list_box___lambda24_ (self=0x555555bb0480, obj=0x555557184a50) at ../src/ConversationList/ConversationListBox.vala:52
#4  0x00005555555ad182 in __mail_conversation_list_box___lambda24__mail_conversation_list_store_row_visibility_func (row=0x555557184a50, self=0x555555bb0480) at ConversationListBox.c:4021
#5  0x00005555555b0007 in mail_conversation_list_store_get_item_internal (self=0x555555e57060, index=84, unfiltered=1) at ../src/ConversationList/ConversationListStore.vala:70
#6  0x00005555555afcd1 in mail_conversation_list_store_real_get_item_unfiltered (base=0x555555e57060, index=84) at ../src/ConversationList/ConversationListStore.vala:41
#7  0x00005555555cd595 in virtualizing_list_box_model_get_item_unfiltered (self=0x555555e57060, index=84) at ../src/VirtualizingListBox/VirtualizingListBoxModel.vala:32
#8  0x00005555555cdc47 in virtualizing_list_box_model_get_index_of_unfiltered (self=0x555555e57060, item=0x555556dc68d0) at ../src/VirtualizingListBox/VirtualizingListBoxModel.vala:100
#9  0x00005555555b0260 in mail_conversation_list_store_remove (self=0x555555e57060, data=0x555556dc68d0) at ../src/ConversationList/ConversationListStore.vala:91
#10 0x00005555555a93dc in mail_conversation_list_box_folder_changed (self=0x555555bb0480, change_info=0x5555573cd760, service_uid=0x555556272ad0 "d58ff581fa52477fa68633040525d9f31e49c170", cancellable=0x555555e4a1a0)
    at ../src/ConversationList/ConversationListBox.vala:232
#11 0x00005555555a74ac in _____________lambda21_ (_data17_=0x5555558092c0, change_info=0x5555573cd760) at ../src/ConversationList/ConversationListBox.vala:164
#12 0x00005555555a74d9 in ______________lambda21__camel_folder_changed (_sender=0x555555e02dc0, changes=0x5555573cd760, self=0x5555558092c0) at ../src/ConversationList/ConversationListBox.vala:164
#13 0x00007ffff7e3c802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7e50814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7e5bbbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7e5c0f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff706890d in  () at /lib/x86_64-linux-gnu/libcamel-1.2.so.62
#18 0x00007ffff7eda04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff7eda400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff7eda4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff72e8fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x00005555555746a2 in _vala_main (args=0x7fffffffdb78, args_length1=2) at ../src/Application.vala:142
#23 0x00005555555746e9 in main (argc=2, argv=0x7fffffffdb78) at ../src/Application.vala:140
```

## Platform Information
* elementary Odin 
* current `master` mail code

**Comment by danrabbit** [comment]
Fixed in #701
