### ISSUE TITLE
Background Process still Crashes

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#768]
### What Happened?

Even though we introduced a crash fix in https://github.com/elementary/mail/pull/760, the background process does still seem to crash with a Segfault when the UI is opened multiple times.

### Steps to Reproduce

1. Kill all running Mail processes: `killall io.elementary.mail`
2. Start the Mail background process: `io.elementary.mail --background`
3. Start the Mail user interface: `io.elementary.mail`
4. Close the Mail user interface
5. Start the Mail user interface a second time: `io.elementary.mail`
6. Watch the Mail background process crashing

### Expected Behavior

The Mail background process should not crash.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

```shell
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `io.elementary.mail --background'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f37cad3a6d9 in g_type_check_instance_is_fundamentally_a () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7f37bfe0fcc0 (LWP 41066))]
(gdb) backtrace
#0  0x00007f37cad3a6d9 in g_type_check_instance_is_fundamentally_a () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007f37cad1b7f0 in g_object_get () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x000055a2075f3651 in mail_conversation_item_model_get_deleted (self=0x55a20b15a750) at ../src/ConversationList/ConversationItemModel.vala:145
#3  0x000055a2075f8904 in mail_conversation_list_box_filter_function (obj=0x55a20b15a750) at ../src/ConversationList/ConversationListBox.vala:343
#4  0x000055a2075f6793 in _mail_conversation_list_box_filter_function_mail_conversation_list_store_row_visibility_func (row=0x55a20b15a750, self=0x0)
    at ConversationListBox.c:1924
#5  0x000055a2075feb4d in mail_conversation_list_store_get_item_internal (self=0x55a2094c04f0, index=6, unfiltered=0)
    at ../src/ConversationList/ConversationListStore.vala:70
#6  0x000055a2075fe7cc in mail_conversation_list_store_real_get_item (base=0x55a2094c04f0, index=6) at ../src/ConversationList/ConversationListStore.vala:37
#7  0x000055a20761c2a3 in virtualizing_list_box_model_get_item (self=0x55a2094c04f0, index=6) at ../src/VirtualizingListBox/VirtualizingListBoxModel.vala:31
#8  0x00007f37ca19b833 in g_list_model_get_object () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x000055a20761e6d4 in virtualizing_list_box_get_widget (self=0x55a2094a04d0, index=6) at ../src/VirtualizingListBox/VirtualizingListBox.vala:208
#10 0x000055a2076200e4 in virtualizing_list_box_insert_bottom_widgets (self=0x55a2094a04d0, bin_height=0x7fffb5f38104)
    at ../src/VirtualizingListBox/VirtualizingListBox.vala:427
#11 0x000055a207620871 in virtualizing_list_box_ensure_visible_widgets (self=0x55a2094a04d0, model_changed=1) at ../src/VirtualizingListBox/VirtualizingListBox.vala:478
#12 0x000055a20761eaca in virtualizing_list_box_on_items_changed (self=0x55a2094a04d0, position=0, removed=0, added=16876)
    at ../src/VirtualizingListBox/VirtualizingListBox.vala:246
#13 0x000055a2076243a6 in _virtualizing_list_box_on_items_changed_g_list_model_items_changed
    (_sender=0x55a2094c04f0, position=0, removed=0, added=16876, self=0x55a2094a04d0) at ../src/VirtualizingListBox/VirtualizingListBox.vala:39
#14 0x00007f37cad12802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f37cad26814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f37cad31bbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f37cad320f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x000055a2075f5ce9 in mail_conversation_list_box_load_folder_co (_data_=0x55a2094a9490) at ../src/ConversationList/ConversationListBox.vala:213
#19 0x000055a2075f45c2 in mail_conversation_list_box_load_folder_ready (source_object=0x55a20914e370, _res_=0x7f37980041a0, _user_data_=0x55a2094a9490)
    at ../src/ConversationList/ConversationListBox.vala:182
#20 0x00007f37ca188f49 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#21 0x00007f37ca188f8d in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#22 0x00007f37cadb004e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f37cadb0400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f37cadb04a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f37ca1b6fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#26 0x000055a2075c0b90 in _vala_main (args=0x7fffb5f38be8, args_length1=2) at ../src/Application.vala:150
#27 0x000055a2075c0bd7 in main (argc=2, argv=0x7fffb5f38be8) at ../src/Application.vala:148
```

### Hardware Info

Dell XPS 9310.

**Comment by marbetschar** [comment]
Maybe related to https://github.com/elementary/mail/issues/787
